[workspace]
members = [
    "web",
    "eagle_macro",
    "shell",
    "macro_consumer",
    "proc_macro_lib",
    "db/mongodb_bin",
    "authority",
    "req/reqwest2",
    "multi_threading/fearless_concurrence",
    "multi_threading/e_crossbeam",
    "file_local",
    "etest",
    "edoc"
]

[profile.dev]
opt-level = 3

