[workspace]
members = [
    "web",
    "eagle_macro",
    "shell",
    "macro_consumer",
    "proc_macro_lib",
    "db/mongodb_async",
    "db/mongodb_sync",
    "authority",
    "req/reqwest2",
    "multi_threading/fearless_concurrence"
]

[profile.dev]
opt-level = 3

