[package]
name = "my_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = { version = "0.5", features = ["capture-spantrace"] } # 使用正确的版本号
